ALTER TABLE journal_entries
    ADD COLUMN IF NOT EXISTS summary TEXT NOT NULL DEFAULT '';

ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS summary TEXT NOT NULL DEFAULT '';

ALTER TABLE experiences
    ADD COLUMN IF NOT EXISTS summary TEXT NOT NULL DEFAULT '';
